TOP=../../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
#
# EVR databases
DB += evr.db
DB += evrWithDelays.db
DB += evrWithExtDelays.db
DB += evrEvent.db
DB += evrEventCtrl.db
DB += evrDevTrig.db
# evrPattern support
DB += evrPatternProc.db
DB += evrEventAll.db
DB += evrPatternAll.db
DB += evrPatternTest.db
DB += evrPatternTestBsa.db
DB += evrMod36.db

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

