TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

# Low-level stats displays
EDL += ioc_stats.edl
EDL += ioc_stats_soft.edl
EDL += ioc_stats_clust.edl
EDL += ioc_stats_clust_rtems.edl
EDL += ioc_stats_limits.edl
EDL += ioc_stats_reboot_confirm.edl

# IOC display per type of IOC
EDL += ioc_rtems_acsw.edl
EDL += ioc_rtems_crat.edl
EDL += ioc_rtems_none.edl
EDL += ioc_rtems_nosupport.edl
EDL += ioc_rtems_power.edl
EDL += ioc_soft.edl
EDL += ioc_softreset_confirm_4.edl
EDL += ioc_softreset_confirm_8.edl
EDL += ioc_softreset_confirm_acsw.edl
EDL += ioc_softreset_confirm_soft.edl
EDL += ioc_softreset_confirm_wiener21.edl
EDL += ioc_softreset_confirm_wiener7.edl
EDL += ioc_screen_demo.edl

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
