# Makefile
TOP = ../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

RESTORES += yyScan.cwConfig
RESTORES += yyScanParmSettings.cwConfig
RESTORES += yyScanPosTables.cwConfig
RESTORES += yyScanSettings.cwConfig

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
