TOP=../..

include $(TOP)/configure/CONFIG

TEMPLATES_DIR = makeBaseApp

TEMPLATES += top/Makefile

## ================================================
## Application TOP needs Documentation
## ================================================
TEMPLATES += top/README
TEMPLATES += top/RELEASE_NOTES
TEMPLATES += top/RELEASE_SITE
## =================================================

TEMPLATES += top/configure/CONFIG
TEMPLATES += top/configure/CONFIG_SITE
TEMPLATES += top/configure/Makefile
TEMPLATES += top/configure/RELEASE
TEMPLATES += top/configure/RULES
TEMPLATES += top/configure/RULES.ioc
TEMPLATES += top/configure/RULES_DIRS
TEMPLATES += top/configure/RULES_TOP

TEMPLATES += top/supportApp/Makefile
TEMPLATES += top/supportApp/Db/Makefile
TEMPLATES += top/supportApp/src/Makefile
TEMPLATES += top/supportApp/src/_APPNAME_.dbd

TEMPLATES += top/iocApp/Makefile
TEMPLATES += top/iocApp/Db/Makefile
TEMPLATES += top/iocApp/src/Makefile
TEMPLATES += top/iocApp/src/_APPNAME_Main.cpp
TEMPLATES += top/iocApp/src/sncExample.stt

TEMPLATES += top/exampleApp/Makefile
TEMPLATES += top/exampleApp/Db/Makefile
TEMPLATES += top/exampleApp/Db/dbExample1.db
TEMPLATES += top/exampleApp/Db/dbExample2.db
TEMPLATES += top/exampleApp/Db/dbSubExample.db
TEMPLATES += top/exampleApp/Db/user.substitutions
TEMPLATES += top/exampleApp/Db/userHost.substitutions
TEMPLATES += top/exampleApp/src/Makefile
TEMPLATES += top/exampleApp/src/xxxRecord.dbd
TEMPLATES += top/exampleApp/src/xxxRecord.c
TEMPLATES += top/exampleApp/src/devXxxSoft.c
TEMPLATES += top/exampleApp/src/xxxSupport.dbd
TEMPLATES += top/exampleApp/src/sncExample.stt
TEMPLATES += top/exampleApp/src/sncProgram.st
TEMPLATES += top/exampleApp/src/sncExample.dbd
TEMPLATES += top/exampleApp/src/dbSubExample.c
TEMPLATES += top/exampleApp/src/dbSubExample.dbd
TEMPLATES += top/exampleApp/src/_APPNAME_Main.cpp
TEMPLATES += top/exampleApp/src/_APPNAME_Hello.c
TEMPLATES += top/exampleApp/src/_APPNAME_Hello.dbd

TEMPLATES += top/exampleBoot/Makefile

TEMPLATES += top/exampleBoot/nfsCommands@vxWorks
TEMPLATES += top/exampleBoot/nfsCommands@vxWorks6

TEMPLATES += top/exampleBoot/nfsCommands@RTEMS
TEMPLATES += top/exampleBoot/ioc/Makefile@Common

TEMPLATES += top/exampleBoot/ioc/Makefile@vxWorks
TEMPLATES += top/exampleBoot/ioc/Makefile@vxWorks6

TEMPLATES += top/exampleBoot/ioc/st.cmd@Common

TEMPLATES += top/exampleBoot/ioc/st.cmd@vxWorks
TEMPLATES += top/exampleBoot/ioc/st.cmd@vxWorks6

TEMPLATES += top/exampleBoot/ioc/st.cmd@RTEMS
TEMPLATES += top/exampleBoot/ioc/README@Common

TEMPLATES += top/exampleBoot/ioc/README@vxWorks
TEMPLATES += top/exampleBoot/ioc/README@vxWorks6

TEMPLATES += top/caClientApp/Makefile
TEMPLATES += top/caClientApp/caExample.c
TEMPLATES += top/caClientApp/caMonitor.c

TEMPLATES += top/caServerApp/Makefile
TEMPLATES += top/caServerApp/README
TEMPLATES += top/caServerApp/exAsyncPV.cc
TEMPLATES += top/caServerApp/exChannel.cc
TEMPLATES += top/caServerApp/exPV.cc
TEMPLATES += top/caServerApp/exScalarPV.cc
TEMPLATES += top/caServerApp/exServer.cc
TEMPLATES += top/caServerApp/exServer.h
TEMPLATES += top/caServerApp/exVectorPV.cc
TEMPLATES += top/caServerApp/main.cc
TEMPLATES += top/caServerApp/test.adl
TEMPLATES += top/caServerApp/vxEntry.cc

TEMPLATES += top/iocBoot/Makefile

TEMPLATES += top/iocBoot/nfsCommands@vxWorks
TEMPLATES += top/iocBoot/nfsCommands@vxWorks6

TEMPLATES += top/iocBoot/nfsCommands@RTEMS
TEMPLATES += top/iocBoot/ioc/Makefile@Common

TEMPLATES += top/iocBoot/ioc/Makefile@vxWorks
TEMPLATES += top/iocBoot/ioc/Makefile@vxWorks6

TEMPLATES += top/iocBoot/ioc/st.cmd@Common
TEMPLATES += top/iocBoot/ioc/st.cmd@Cross

TEMPLATES += top/iocBoot/ioc/st.cmd@vxWorks
TEMPLATES += top/iocBoot/ioc/st.cmd@vxWorks6

TEMPLATES += top/iocBoot/ioc/st.cmd@RTEMS


## ============================================
## LCLS Style Templates (Added by ELW)
## ============================================
TEMPLATES += top/lclsApp/Makefile
TEMPLATES += top/lclsApp/Db/Makefile
TEMPLATES += top/lclsApp/Db/dbExample1.db
TEMPLATES += top/lclsApp/Db/dbExample2.db
TEMPLATES += top/lclsApp/Db/dbSubExample.db
TEMPLATES += top/lclsApp/src/Makefile
TEMPLATES += top/lclsApp/src/xxxRecord.dbd
TEMPLATES += top/lclsApp/src/xxxRecord.c
TEMPLATES += top/lclsApp/src/devXxxSoft.c
TEMPLATES += top/lclsApp/src/xxxSupport.dbd
TEMPLATES += top/lclsApp/src/sncExample.stt
TEMPLATES += top/lclsApp/src/sncProgram.st
TEMPLATES += top/lclsApp/src/sncExample.dbd
TEMPLATES += top/lclsApp/src/dbSubExample.c
TEMPLATES += top/lclsApp/src/dbSubExample.dbd
TEMPLATES += top/lclsApp/src/_APPNAME_Main.cpp
TEMPLATES += top/lclsApp/src/_APPNAME_Hello.c
TEMPLATES += top/lclsApp/src/_APPNAME_Hello.dbd

TEMPLATES += top/lclsApp/srcDisplay/Makefile
TEMPLATES += top/lclsApp/srcDisplay/example.edl

TEMPLATES += top/lclsApp/srcRestore/Makefile
TEMPLATES += top/lclsApp/srcRestore/example.cwConfig

TEMPLATES += top/lclsBoot/Makefile

TEMPLATES += top/lclsBoot/nfsCommands@vxWorks
TEMPLATES += top/lclsBoot/nfsCommands@vxWorks6

TEMPLATES += top/lclsBoot/nfsCommands@RTEMS
TEMPLATES += top/lclsBoot/ioc/Makefile@Common

TEMPLATES += top/lclsBoot/ioc/Makefile@vxWorks
TEMPLATES += top/lclsBoot/ioc/Makefile@vxWorks6

TEMPLATES += top/lclsBoot/ioc/st.cmd@Common
TEMPLATES += top/lclsBoot/ioc/st.cmd@Cross

TEMPLATES += top/lclsBoot/ioc/st.cmd@vxWorks
TEMPLATES += top/lclsBoot/ioc/st.cmd@vxWorks6

TEMPLATES += top/lclsBoot/ioc/st.cmd@RTEMS
TEMPLATES += top/lclsBoot/ioc/README@Common

TEMPLATES += top/lclsBoot/ioc/README@vxWorks
TEMPLATES += top/lclsBoot/ioc/README@vxWorks6

## ==========================================
## End Changes needed for LCLS ==============
## ==========================================



SCRIPTS_HOST += makeBaseApp.pl

include $(TOP)/configure/RULES

