TOP=..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

RESTORES += trigXL05.cwConfig

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

