# Makefile
TOP = ../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

RESTORES +=  yy10Sseq.cwConfig
RESTORES +=  yy10UserCalcs.cwConfig
RESTORES +=  yy10UserStringCalcs.cwConfig
RESTORES +=  yy10UserTrans.cwConfig
RESTORES +=  yyStringCalcSettings.cwConfig
RESTORES +=  yyTransformSettings.cwConfig
RESTORES +=  yyWaitSettings.cwConfig

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
