# EPICS R3.14 Makefile for the Daemon
TOP=../../..
include $(TOP)/configure/CONFIG
include $(TOP)/src/ChannelArchiver/make.cfg

include $(TOP)/configure/RULES

arch:
	cp *.pm *.pl *.sh /arch/scripts

