TOP=../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

#==================================================
# build a support library

#LIBRARY_IOC += count

# xxxRecord.h will be created from xxxRecord.dbd
#DBDINC += xxxRecord
# install epm2000.dbd into <top>/dbd
#DBD += epm2000.dbd

# specify all source files to be compiled and added to the library
#epm2000_SRCS += xxx

#epm2000_LIBS += $(EPICS_BASE_IOC_LIBS)

#===========================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

