#*************************************************************************
# Copyright (c) 2006 UChicago Argonne LLC, as Operator of Argonne
#     National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
#     Operator of Los Alamos National Laboratory.
# EPICS BASE is distributed subject to a Software License Agreement found
# in the file LICENSE that is included with this distribution. 
#*************************************************************************
#
# Makefile,v 1.41.2.8 2006/12/20 21:21:44 jba Exp
#

TOP = ..
include $(TOP)/configure/CONFIG

DIRS += libCom
DIRS += ca
DIRS += toolsComm
DIRS += dbStatic
DIRS += registry
DIRS += bpt
DIRS += db
DIRS += as
DIRS += util
DIRS += dbtools
DIRS += catools
DIRS += rsrv
DIRS += rec
DIRS += dev
DIRS += misc
DIRS += iocsh
DIRS += RTEMS
DIRS += libCom/test
DIRS += db/test
DIRS += vxWorks
DIRS += softIoc
DIRS += gdd
DIRS += cas
DIRS += makeBaseApp
DIRS += excas
DIRS += makeBaseExt

include $(TOP)/configure/RULES_DIRS

