#!/bin/sh

v=`xmlrpc-c-config --version`

case $v in
  1.0*) client="client"
        ;;
  0.*)  client="libwww-client"
        ;;
  *)    echo "Cannot run or decode 'xmlrpc-c-config'"
	exit 1
esac

case $1 in
   server-flags)   xmlrpc-c-config cgi-server --cflags
		   ;;
   cgi-libs)       xmlrpc-c-config cgi-server --libs
                   ;;
   abyss-libs)     xmlrpc-c-config abyss-server --libs
                   ;;
   client-libs)    xmlrpc-c-config $client --libs
                   ;;
   *)              echo "USAGE: See source code"
                   exit 2
esac

