TOP=../../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
#

DB += evrDevTrig.db

# Laser Room and Injector Laser Steering
DB += IOC-LR20-LS01evr.db
DB += IOC-LR20-LS02evr.db
DB += IOC-IN20-LS11evr.db  
DB += IOC-IN20-LS12evr.db  
DB += IOC-IN20-LS13evr.db  
DB += IOC-IN20-LS14evr.db  
DB += IOC-IN20-LS15evr.db  
DB += IOC-IN20-LS16evr.db  
DB += IOC-IN20-LS17evr.db  
DB += IOC-IN20-LS18evr.db  
DB += IOC-IN20-LS19evr.db  
DB += IOC-LR20-LS01pattern.db
DB += IOC-LR20-LS02pattern.db
DB += IOC-IN20-LS11pattern.db  
DB += IOC-IN20-LS12pattern.db  
DB += IOC-IN20-LS13pattern.db  
DB += IOC-IN20-LS14pattern.db  
DB += IOC-IN20-LS15pattern.db  
DB += IOC-IN20-LS16pattern.db  
DB += IOC-IN20-LS17pattern.db  
DB += IOC-IN20-LS18pattern.db  
DB += IOC-IN20-LS19pattern.db
DB += IOC-LR20-LS01trig.db
DB += IOC-LR20-LS02trig.db
DB += IOC-IN20-LS11trig.db
DB += IOC-IN20-LS12trig.db  
DB += IOC-IN20-LS13trig.db 
DB += IOC-IN20-LS14trig.db 
DB += IOC-IN20-LS15trig.db 
CW += IOC-LR20-LS01trig.cwConfig
CW += IOC-LR20-LS02trig.cwConfig
CW += IOC-IN20-LS11trig.cwConfig
CW += IOC-IN20-LS12trig.cwConfig
CW += IOC-IN20-LS13trig.cwConfig
CW += IOC-IN20-LS14trig.cwConfig
CW += IOC-IN20-LS15trig.cwConfig
DB += IOC-IN20-LS11bsa.db  

# Profile Monitor - Injector and Linac
DB += IOC-IN20-PM01evr.db
DB += IOC-IN20-PM02evr.db
DB += IOC-IN20-PM03evr.db
DB += IOC-IN20-PM04evr.db
DB += IOC-IN20-PM05evr.db
DB += IOC-IN20-PM06evr.db
DB += IOC-IN20-PM07evr.db
DB += IOC-LI21-PM01evr.db
DB += IOC-LI25-PM01evr.db
DB += IOC-IN20-PM01pattern.db
DB += IOC-IN20-PM02pattern.db
DB += IOC-IN20-PM03pattern.db
DB += IOC-IN20-PM04pattern.db
DB += IOC-IN20-PM05pattern.db
DB += IOC-IN20-PM06pattern.db
DB += IOC-IN20-PM07pattern.db
DB += IOC-LI21-PM01pattern.db
DB += IOC-LI25-PM01pattern.db
DB += IOC-IN20-PM01trig.db
DB += IOC-IN20-PM02trig.db
DB += IOC-IN20-PM03trig.db
DB += IOC-IN20-PM04trig.db
DB += IOC-IN20-PM05trig.db
DB += IOC-IN20-PM06trig.db
DB += IOC-IN20-PM07trig.db
DB += IOC-LI21-PM01trig.db
DB += IOC-LI25-PM01trig.db
CW += IOC-IN20-PM01trig.cwConfig
CW += IOC-IN20-PM02trig.cwConfig
CW += IOC-IN20-PM03trig.cwConfig
CW += IOC-IN20-PM04trig.cwConfig
CW += IOC-IN20-PM05trig.cwConfig
CW += IOC-IN20-PM06trig.cwConfig
CW += IOC-IN20-PM07trig.cwConfig
CW += IOC-LI21-PM01trig.cwConfig
CW += IOC-LI25-PM01trig.cwConfig

# Injector - MPS, Alignment Mirror, Event
DB += IOC-IN20-MP01evr.db
DB += IOC-IN20-MP01pattern.db
DB += IOC-IN20-MP01trig.db
DB += IOC-IN20-MP01trig.cwConfig
DB += IOC-IN20-AM01evr.db  
DB += IOC-IN20-AM01pattern.db 
DB += IOC-IN20-AM01trig.db
CW += IOC-IN20-AM01trig.cwConfig
#DB += IOC-IN20-EV01evr.db
#DB += IOC-IN20-EV01pattern.db

# Bunch Length and Current Monitor - Injector and Linac
DB += IOC-IN20-IM01evr.db  
DB += IOC-IN20-IM01pattern.db
DB += IOC-IN20-IM01bsa.db
DB += IOC-IN20-IM01trig.db
CW += IOC-IN20-IM01trig.cwConfig
DB += IOC-LI21-BL01evr.db
DB += IOC-LI21-BL01pattern.db
DB += IOC-LI21-BL01bsa.db
DB += IOC-LI21-BL01trig.db
CW += IOC-LI21-BL01trig.cwConfig

# RF and Motion Control - Injector and Linac
DB += IOC-IN20-MC01evr.db
DB += IOC-IN20-MC01pattern.db
DB += IOC-IN20-MC01bsa.db
DB += IOC-IN20-MC01trig.db
CW += IOC-IN20-MC01trig.cwConfig
DB += IOC-IN20-RF01evr.db
DB += IOC-IN20-RF01Testevr.db
DB += IOC-IN20-RF01pattern.db
DB += IOC-IN20-RF01bsa.db
DB += IOC-IN20-RF01trig.db
CW += IOC-IN20-RF01trig.cwConfig
DB += IOC-LI21-RF01bsa.db
DB += IOC-LI24-RF01bsa.db

# Magnet - Injector and Linac 
DB += IOC-IN20-MG01evr.db  
DB += IOC-IN20-MG01pattern.db  
DB += IOC-LI21-MG01evr.db
DB += IOC-LI21-MG01pattern.db

# BPM - Injector and Linz
DB += IOC-IN20-BP01evr.db  
DB += IOC-IN20-BP01Testevr.db  
DB += IOC-IN20-BP01pattern.db  
DB += IOC-IN20-BP01bsa.db
DB += IOC-IN20-BP01trig.db 
CW += IOC-IN20-BP01trig.cwConfig
DB += IOC-IN20-BP02evr.db  
DB += IOC-IN20-BP02pattern.db  
DB += IOC-IN20-BP02bsa.db
DB += IOC-IN20-BP02trig.db 
CW += IOC-IN20-BP02trig.cwConfig 
DB += IOC-LI21-BP01evr.db
DB += IOC-LI21-BP01pattern.db
DB += IOC-LI21-BP01bsa.db
DB += IOC-LI21-BP01trig.db
CW += IOC-LI21-BP01trig.cwConfig

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
include $(TOP)/configure/RULES.Db
include $(TOP)/configure/RULES.Cw


