TOP=../../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
#
# Device Simulation
DB += bsaBPMSTest.db
DB += bsaTOROTest.db
DB += bsaBLENTest.db
DB += bsaWIRETest.db
DB += bsaPMTTest.db
DB += bsaFARCTest.db
# Device edef records
DB += bsaBPMSEdef.db
DB += bsaBPMSCavityEdef.db
DB += bsaTOROEdef.db
DB += bsaFARCEdef.db
DB += bsaBLENEdef.db
DB += bsaPMTEdef.db
DB += bsaWIREEdef.db
DB += bsaAMPLEdef.db
DB += bsaPHASEdef.db
DB += bsaPWREdef.db
DB += bsaEnergyEdef.db

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

