TOP=..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
#
# Test stands
DB += evrEV02.db
DB += evrXL04.db
DB += evrXL05.db
DB += evrXL09.db
DB += evrXL16.db
DB += evrBP21.db
DB += evrTO20.db
DB += evrPatternEV02.db
DB += evrPatternXL04.db
DB += evrPatternXL05.db
DB += evrPatternXL09.db
DB += evrPatternXL16.db
DB += evrPatternBP21.db
DB += evrPatternTO20.db
DB += trigXL04.db
DB += trigXL05.db
DB += trigXL09.db
DB += trigXL16.db
# MPS Test
DB += mpsEvr.db
DB += mpsEvrPattern.db

# BSA Test Stands
DB += bsaXL01.db
DB += bsaSimXL01.db
DB += bsaXL02.db
DB += bsaSimXL02.db
DB += bsaXL03.db
DB += bsaSimXL03.db
DB += bsaXL04.db
DB += bsaSimXL04.db
DB += bsaXL05.db
DB += bsaSimXL05.db
DB += bsaXL09.db
DB += bsaXL16.db
DB += bsaSimXL09.db
DB += bsaBP21.db
DB += bsaSimBP21.db
DB += bsaTO20.db
DB += bsaSimTO20.db

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

