TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
DB += Bx9000Info.template
DB += Bx9000InstalledBTs.template
DB += KL1104.template
DB += KL1124.template
DB += KL1408.template
DB += KL2124.template
DB += KL2408.template
DB += KL2622.template
DB += KL3064.template
DB += KL3102.template
DB += KL3312.template
DB += KL3314.template
DB += KL3408.template
DB += KL3468.template
DB += KL4002.template
DB += KL4132.template

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
include $(TOP)/configure/RULES.Db
#----------------------------------------
#  ADD RULES AFTER THIS LINE

